name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 23

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
    - name: Run tests
      run: make gh-test
